// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANhnFOZHjEaWsF0zEOgEMbBzTmSgQIu6s',
    appId: '1:1009255822324:web:b92f20c6e7722cfdc17fa1',
    messagingSenderId: '1009255822324',
    projectId: 'a2ui-850ec',
    authDomain: 'a2ui-850ec.firebaseapp.com',
    storageBucket: 'a2ui-850ec.firebasestorage.app',
    measurementId: 'G-3CQPXTF8EF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9Hh1S6jjr3NVEmPQX8xT4i0pwECSczn0',
    appId: '1:1009255822324:android:b314bac2a3702c9dc17fa1',
    messagingSenderId: '1009255822324',
    projectId: 'a2ui-850ec',
    storageBucket: 'a2ui-850ec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEvwX3F-EjKFnTLO_x9HSny4h41bjSvVk',
    appId: '1:1009255822324:ios:5bb6fe60bf499864c17fa1',
    messagingSenderId: '1009255822324',
    projectId: 'a2ui-850ec',
    storageBucket: 'a2ui-850ec.firebasestorage.app',
    iosBundleId: 'com.lgcns.testApp.a2ui',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEvwX3F-EjKFnTLO_x9HSny4h41bjSvVk',
    appId: '1:1009255822324:ios:f1ed11b78efa9a3ec17fa1',
    messagingSenderId: '1009255822324',
    projectId: 'a2ui-850ec',
    storageBucket: 'a2ui-850ec.firebasestorage.app',
    iosBundleId: 'com.example.a2ui',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANhnFOZHjEaWsF0zEOgEMbBzTmSgQIu6s',
    appId: '1:1009255822324:web:9c4c4e06bdd44c6fc17fa1',
    messagingSenderId: '1009255822324',
    projectId: 'a2ui-850ec',
    authDomain: 'a2ui-850ec.firebaseapp.com',
    storageBucket: 'a2ui-850ec.firebasestorage.app',
    measurementId: 'G-65Q9V781Z8',
  );
}
